### ISSUE TITLE
domain cannot be executed from node 

### ISSUE THREAD

**Issue by juanmaguitar** [trainings-juanmaguitar/schibsted-sui-tools-training-dec2018#19]
Demo at `stuff/demos/domain-demo` cannot be launched from node.js
How can i do it? It should work by:
- installing `babel-preset-sui`
- having the following `.babelrc` → `{ "presets": ["sui"] }`
- launching `babel-node index.js`

right?

Now I get...

```
⬢  domain-demo  devel ⦿ npm start

> domain-demo@1.0.0 start /Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo
> babel-node index.js

/Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/@babel/core/lib/config/config-descriptors.js:178
    throw new Error(`Plugin/Preset files are not allowed to export objects, only functions. In ${filepath}`);
    ^

Error: Plugin/Preset files are not allowed to export objects, only functions. In /Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/babel-preset-sui/lib/index.js
    at createDescriptor (/Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Volumes/RINGO/PROJECTS/2018/SCHIBSTED/training-sui/schibsted-sui-tools-training/stuff/demos/domain-demo/node_modules/@babel/core/lib/config/partial.js:85:55)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! domain-demo@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the domain-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juanmanuelgarrido/.npm/_logs/2018-12-13T09_19_30_303Z-debug.log
```

**Comment by midudev** [comment]
You might be using @babel/node instead the old babel-node. 

For now, `babel-preset-sui` is only compatible with babel@6. We're working on it (https://github.com/SUI-Components/sui/pull/367) but still not ready. 

So, you need to install old babel-core and babel-node in order to make it work.

**Comment by juanmaguitar** [comment]
Solved w/ this `package.json`

```
{
  "name": "domain-demo",
  "version": "1.0.0",
  "description": "",
  "main": "lib/index.js",
  "scripts": {
    "demo": "npm run build && node demo.js",
    "build": "npx rimraf lib && babel src --out-dir lib"
  },
  "private": true, 
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@s-ui/lint": "2.20.0",
    "@babel/core": "^7.2.0",
    "@babel/node": "^7.2.0",
    "babel-plugin-add-module-exports": "^1.0.0"
  },
  "dependencies": {
    "@s-ui/domain": "1.12.0"
  },
  "babel": {
    "presets": [
      "sui"
    ],
    "plugins": [
      "add-module-exports"
    ]
  },
  "eslintConfig": {
    "extends": [
      "./node_modules/@s-ui/lint/eslintrc.js"
    ]
  },
  "sasslintConfig": "./node_modules/@s-ui/lint/sass-lint.yml"
}

```
